### ISSUE TITLE
Late-game bloodstem could be used to mass produce blood bags for Blood IV

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#35]
A late-game / mid-game research could unlock a new feature of bloodstem that allows it to be combined with another resource to produce blood bags - an almost unlimited source of blood for blood IV's. This'd make it far easier to produce blood bags as it's likely that it'd require significant time or resources otherwise.

**Comment by ghost** [comment]
This could be interesting.  The only concern I have is that, thematically, bloodstem is described and used predominantly to clot blood.  I.e. the plant has some useful protein or chemical in it that can be extracted and used to clot blood.

Blood is made of around 50% red blood cells and 50% plasma (fluid with some other stuff).  About 1% is made up of white blood cells and platelets (the primary blood clotting proteins).  Since such a small percentage of blood is actually composed of platelets, it would seem a bit counterintuitive to manufacture blood bags out of a plant which has a significant concentration of blood clotting elements.

IRL when a patient is undergoing hypovolemic shock (hypo = less, volemia = volume), such as due to severe blood loss in trauma situations, a critical response is to [replace the lost fluid](https://en.wikipedia.org/wiki/Fluid_replacement#Intravenous).  This is often initially achieved with IV infusions like normal saline (0.9% sodium chloride - basically salt water at the same concentration as blood) and Lactated Ringer's solution (contains some other electrolytes as well).  Blood transfusions can be done, but blood is typically harder to get and less readily available in large quantities (especially if you don't know the blood type of the patient).  Often, normal saline or Lactated Ringer's solution is given IV to fix the low blood volume, and then when the patient in less of an emergency they begin giving blood transfusions.

I would suggest that perhaps solutions like normal saline and Lactated Ringer's can be used as an alternative to the artificial blood bags.  Normal saline is literally just salt water, although it has to be made a specific concentration and sterile.  If you want to gate it behind research or skill level, perhaps you could require a high intelligence or medicine skill and some sort of sterile pharmaceuticals research (maybe for all IVs, since all have to be sterile).

I'm not sure where you would get salt from, however... modern salt production comes either from evaporating sea water or from mining halite (rock salt).  Looks like halite can be found all over the world, so it may be possible to include as an ore if you're inclined to make it a natural resource.  Salt can of course be used for many things IRL, the most relevant to RW being food preservation - salt pork was historically a popular military ration - [here is a great resource](https://savoringthepast.net/2016/03/30/preparing-salt-pork/) on its production and usage.  I think at this point it would be too much feature creep, though - the mod shouldn't be concerned with things beyond its scope.  Perhaps if you're interested in pursuing salt and preservation further, it would be best as a separate mod or even a core mod if that's a thing in RW modding.

**Comment by I-Knight-I** [comment]
Hm, I was thinking quite simply along the lines of it literally being called "blood"stem and already have some affect on the pawn's blood. I envisioned some Spacer tech that essentially 'unlocks' or removes unnecessary properties of the bloodstem to form an even greater function for it. Literally something fantasy and Rimworldy to aid gameplay more and make it less tedious for the player. 

I think with all late-game stuffs which can't really be explained with modern logic or medicine we just throw "mechanites" into it and make it more fun. What's your thoughts on this? I wouldn't mind making it more complex but it would be more work for the both of us haha.

**Comment by ghost** [comment]
I think anything can be explained with spacer tech too.  That should be fine then!
