### ISSUE TITLE
Strokes

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#47]
Caused by low mood. Could be available to those who anxiety disorders or depression ONLY and could be a MTB health issue? Seems unreasonable to give a chance for it to everyone.

**Comment by ghost** [comment]
You may have another disorder in mind?  Strokes are usually caused by either a blood clot in the brain's circulation (ischemic stroke) or when blood fills a portion of the skull and the pressure on brain tissue cuts off circulation (hemorrhagic stroke).

More info: http://www.stroke.org/understand-stroke/what-stroke

In theory I suppose a stroke could happen to anyone (as is the case with any disease), but [those at high risk](https://www.strokeassociation.org/STROKEORG/AboutStroke/UnderstandingRisk/Understanding-Stroke-Risk_UCM_308539_SubHomePage.jsp) include those with:
- High blood pressure
- Smokers
- Diabetes
- Obesity/poor diet/poor exercise
- Cardiovascular diseases
- Atrial fibrillation (a chronic disorder which often develops after having a heart attack)

**Comment by I-Knight-I** [comment]
I could've sworn strokes were caused by stress. Maybe that's an urban myth. I'll close this and add it to #50
