### ISSUE TITLE
Anxiety Disorder - trait

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#48]
Lowers movement speed (nervousness and lack of confidence) and makes the pawn incapable of certain jobs like violence or socialising. Also can lead to insomnia if the pawn is under constant stress?

**Comment by ghost** [comment]
I don't think anxiety should lead to strokes.  Physiologically, I can't think of a good explanation for why anxiety would directly cause strokes.  They can coexist however, since people with anxiety may have a higher prevalence of high-risk behaviors like smoking and poor lifestyle habits, which are known to increase risk of stroke.

**Comment by I-Knight-I** [comment]
Removed strokes from original post. Got confused.

**Comment by I-Knight-I** [comment]
Anxiety is added through Psychology mod as well as PTSD. Might put this on the backburner because of that. Might not add at all.
