### ISSUE TITLE
Death Rattle adds "intestinal failure" - ICU machine for this?

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#51]

**Comment by ghost** [comment]
Any idea what causes this?  The only thing I can think of is destroying or removing stomach.

AFAIK, there is no ICU machine to replace the intestines or stomach.  IRL if your stomach or intestines were to be destroyed by trauma (e.g. gunshot, stabbing), your main concern would be rapid blood loss due to the damage done to blood vessels.    Of course you would want to stop the bleeding as well.  Blood loss can be treated with fluid resuscitation (i.e. blood transfusion or, more commonly, IV normal saline - see #35 ).  To repair the damage and stop internal bleeding would require emergency surgery, although it seems vanilla RW can use medicine and doctoring to heal any bleeding.

A secondary issue of concern is sepsis, i.e. widespread infection.  This is always a concern in traumatic situations, but due to the fact that the intestines have so much bacteria in them, damaging them can release germs into your body where they can spread to surrounding tissue and the bloodstream.  When this happens, your body reacts with widespread inflammation.  Without going into too much detail, basically what happens is your body takes fluid out of the blood stream and moves it to where the infection or trauma is.  This allows white blood cells etc. to rush to the site of injury/infection and begin healing it.  You can see this happening when you suffer a scrape - the area becomes red and swollen, and clear liquid oozes out as it heals.  This is useful, but when there is too much infection and injury, such as in the case of sepsis, this inflammatory response goes overboard.  Suddenly, your blood volume is decreased due to the inflammation removing too much fluid - this can be made worse if there is still bleeding.  Septic shock is the name we use when this happens - it is similar to hypovolemic shock in that there is a loss of blood pressure and volume.  However, in the case of septic shock, it is due to sepsis instead of blood loss.  It is similarly treated with fluid resuscitation, but IV antibiotics are also used to address any infection.

In the case of severe gastrointestinal trauma (e.g. stomach destroyed, part of the intestines destroyed), surgery may be required to remove the damaged portion and simply attach the remaining healthy portions together.  This is probably too advanced for the scope of the mod, however.

**Comment by I-Knight-I** [comment]
> In the case of severe gastrointestinal trauma (e.g. stomach destroyed, part of the intestines destroyed), surgery may be required to remove the damaged portion and simply attach the remaining healthy portions together. This is probably too advanced for the scope of the mod, however.

Hm, well a simple surgery bill for this isn't too difficult. We definitely could add it and only make the bill available to those with the intestinal failure hediff. I'm not too sure how much time they'd have for this, however. It could be a lost cause at that point. 

As for the infection part - we could definitely add another problem on top of the life-threatening issue already there but, again, I'm not sure how much time the player would have to treat the pawn anyway and so it might not make any difference if they're going to die regardless. We could look at some 'hacky' ways of making the hediff last longer before death but how effective would that be given the options available to the player.

Maybe there's some other ways we could edit and incorporate / heal and deal with intestinal failure. 

Also, I'll look now and edit this comment to say what causes the issue. I would also assume the stomach becomes severely damaged or destroyed but I'll double check... Yup. It's missing stomach.

EDIT: It's also worth noting that "Intestinal Failure" hediff goes up _extremely slowly_. This allows us to look into genuine options and medical treatments. It takes roughly 2.5 - 3 days before a pawn would actually die from this issue! I think that just means that we should definitely add something else to counter this hediff that isn't literally "give a person a new stomach". 

My thoughts are that we might be able to salvage a small section of the severely damaged stomach and use that as a solution when no implant is available. Something like (and bare with me here) gastric bypass surgery where a lot of the stomach is 'skipped' to make it smaller - I could be wrong but I think that's the gist of it. In-game this'd look like a blue hediff on the pawns health tab and would essentially act as an implant that isn't as effective as the full part (like EPOE). Using this method we could make the pawn's metabolism 50% (or less) and their stomach no longer able to receive this surgery a second time but still able to be damaged. In the unlikely event it is majorly damaged twice then they would require a full organ implant or they will die. 

More technically - we could restore the stomach when the surgery happens but limit its part effectiveness to something like 0.50. This allows it to still be damaged and would allow us to integrate the second part of the above where the surgery can only be applied once. Doing this would allow the "intestinal failure" hediff to actually disappear altogether too and would prevent any bugs or the need for constant scripting that reduces the severity of the hediff that'd otherwise damage performance (important to note: ICU machines do not prevent the hediff from ticking up but rather just remove it constantly but that's because the machines are always within range of the pawn). This might be fairly straightforward to implement.

**Comment by ghost** [comment]
This seems like a good solution.  As mentioned, IRL when the intestinal tract/stomach is damage, surgery is done to basically reroute things and remove the damages portion.  A bypass is very similar to that.  I think the suggestion of restoring the stomach and limiting its efficiency is a good way to handle it without having to add in too much new code/functionality.

**Comment by I-Knight-I** [comment]
Glad you like it, I can get working on it now. I didn't know how realistic this'd be at first, that's why I hesitated to make it "In Progress"

**Comment by I-Knight-I** [comment]
Going to add infection in the stomach when the pawn gets the surgery to recover it. Won't reopen issue, will address this now.
